---
name: listen
version: '3.9'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 14112a82013860a7d2e5246b4c4f36fbb8c349dc
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
