module NamePlate
  module ViewHelpers
    # Rails view helpers for rendering avatars in controllers/views.
    #
    # Usage in Rails:
    #   include NamePlate::ViewHelpers::Avatar
    #
    # Then in your views:
    #   letter_avatar_for("Tony", 200)
    #   letter_avatar_url("Tony", 200)
    #   letter_avatar_tag("Tony", 200, class: "avatar")
    module Avatar
      # Return path to generated avatar image
      #
      # @param name [String] the name to base avatar on
      # @param size [Integer] requested size in px
      # @return [String] filesystem path
      def letter_avatar_for: (untyped name, ?::Integer size) -> untyped

      # Return URL for generated avatar image
      #
      # @param name [String] the name to base avatar on
      # @param size [Integer] requested size in px
      # @return [String] URL path
      def letter_avatar_url: (untyped name, ?::Integer size) -> untyped

      # Render an <img> tag for the avatar
      #
      # @param name [String] the name to base avatar on
      # @param size [Integer] requested size
      # @param options [Hash] HTML options (e.g., :class)
      # @return [String] HTML img tag
      def letter_avatar_tag: (untyped name, ?::Integer size, ?::Hash[untyped, untyped] options) -> untyped

      extend ActionView::Helpers::AssetTagHelper

      def image_tag: (String path, ?Hash[untyped, untyped] options) -> String
    end
  end
end
