module NamePlate
  module Colors
    # Base class for all color Palette.
    class Palette
      @colors: untyped

      attr_reader colors: untyped

      def initialize: (untyped colors) -> void

      # Select a color based on a username string.
      #
      # @param username [String]
      # @return [Array<Integer>] RGB triplet
      def pick: (untyped username) -> untyped

      private

      def hash_index: (untyped username) -> untyped
    end
  end
end
