module MiniMagick
  # Provides high-level image API (open, write, etc.)
  class Image
  end

  # Command builder for ImageMagick's `convert`
  class Tool
    class Convert
      def self.new: () -> Convert
      def size: (String) -> void
      def pointsize: (String) -> void
      def font: (String) -> void
      def weight: (String) -> void
      def fill: (String) -> void
      def gravity: (String) -> void
      def annotate: (String, String) -> void
      def << : (String) -> void
      def call: () -> void
    end
  end
end
